"""Shared contracts for the Word formula remediation pipeline."""

from .contract import (
    ArtifactState,
    Confidence,
    ContractError,
    DEFAULT_REQUIRED_GATES,
    DeliveryStatus,
    Gate,
    GateState,
    Manifest,
    OccurrenceStatus,
    SourceType,
    FrozenJob,
    bind_gate_evidence,
    derive_job_status,
    deterministic_occurrence_id,
    dump_job,
    freeze_job,
    load_job,
    load_manifest,
    set_artifact_content,
    set_occurrence_status,
    verify_frozen_job,
)
from .canonical import CanonicalError, canonical_equal, canonical_json, canonicalize, canonicalize_formula
from .recovery import (
    EVIDENCE_RANKS,
    RecoveryError,
    RecoveryResult,
    Transformation,
    recover_formula,
    recover_manifest,
    recovery_fingerprint,
)

__all__ = [
    "ArtifactState",
    "Confidence",
    "ContractError",
    "DEFAULT_REQUIRED_GATES",
    "DeliveryStatus",
    "Gate",
    "GateState",
    "Manifest",
    "OccurrenceStatus",
    "SourceType",
    "FrozenJob",
    "bind_gate_evidence",
    "derive_job_status",
    "deterministic_occurrence_id",
    "dump_job",
    "freeze_job",
    "load_job",
    "load_manifest",
    "set_artifact_content",
    "set_occurrence_status",
    "verify_frozen_job",
    "CanonicalError",
    "canonical_equal",
    "canonical_json",
    "canonicalize",
    "canonicalize_formula",
    "EVIDENCE_RANKS",
    "RecoveryError",
    "RecoveryResult",
    "Transformation",
    "recover_formula",
    "recover_manifest",
    "recovery_fingerprint",
]
